name: Overlay

on:
  workflow_dispatch:
  pull_request:
    branches: [pie]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@latest

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install git-core git xmlstarlet

    - name: Run test scripts
      run: |
        cd tests
        bash tests.sh

    - name: Build APKs
      run: |
        cd build
        bash build.sh

    - name: Upload APKs
      uses: actions/upload-artifact@latest
      with:
        path: build/*.apk
        name: Overlays
